# Confidence Algorithm Configuration
# This file defines the parameters and rules for the pattern confidence tracking system

# Core Algorithm Parameters
confidence_algorithm:
  # Initial confidence for newly discovered patterns
  initial_confidence: 0.5

  # Confidence adjustment parameters
  success_increment: 0.1      # Added to confidence on successful application
  failure_decrement: 0.2      # Subtracted from confidence on failed application

  # Confidence bounds
  max_confidence: 0.95        # Maximum allowed confidence score
  min_confidence: 0.1         # Minimum allowed confidence score

  # Adaptation parameters
  adaptation_rate: 0.05       # Rate at which confidence adapts to new evidence
  context_weight: 0.3         # Weight given to context similarity
  recency_weight: 0.2         # Weight given to recency of applications
  diversity_weight: 0.1       # Weight given to diversity of application contexts

# Decision Thresholds
# Confidence levels required for different types of pattern application
decision_thresholds:
  auto_apply: 0.8            # Patterns with confidence >= 0.8 are auto-applied
  recommend: 0.6             # Patterns with confidence >= 0.6 are recommended
  experimental: 0.4          # Patterns with confidence >= 0.4 can be experimentally applied
  deprecated: 0.2            # Patterns with confidence < 0.2 are deprecated

# Confidence Decay Configuration
# Automatic confidence reduction for unused patterns
confidence_decay:
  enabled: true
  decay_rate: 0.02           # Monthly decay rate (2% per month)
  usage_threshold_days: 30   # Days without usage before decay applies
  min_decay_confidence: 0.3  # Minimum confidence after decay
  decay_calculation_method: "exponential"

# Pattern Application Limits
# Safety limits to prevent over-application of patterns
application_limits:
  max_applications_per_session: 3
  cooldown_period_minutes: 60
  min_confidence_threshold: 0.5
  requires_human_approval: false

# Context Matching Weights
# Weights for different context factors in similarity calculation
context_weights:
  security_context: 1.0
  performance_context: 0.9
  architecture_context: 0.8
  quality_context: 0.7
  integration_context: 0.6
  deployment_context: 0.5

# Success Rate Calculation
# Parameters for calculating pattern success rates
success_calculation:
  minimum_applications: 3     # Minimum applications before calculating success rate
  recency_bias: 0.3          # Weight given to recent applications
  context_similarity_weight: 0.2  # Weight given to context similarity
  quality_impact_weight: 0.5     # Weight given to quality impact

# Adaptation Triggers
# Conditions that trigger automatic pattern adaptation
adaptation_triggers:
  - condition: "success_rate_below_threshold"
    threshold: 0.5
    action: "reduce_confidence"
    adjustment: -0.1

  - condition: "consistent_failures"
    threshold: 3
    action: "reduce_confidence"
    adjustment: -0.2

  - condition: "high_success_rate"
    threshold: 0.9
    action: "increase_confidence"
    adjustment: 0.05

  - condition: "context_drift"
    threshold: 0.7
    action: "refine_context_matching"

# Pattern Lifecycle Management
pattern_lifecycle:
  experimental_phase:
    min_applications: 1
    max_applications: 5
    confidence_target: 0.6

  validation_phase:
    min_applications: 6
    max_applications: 15
    confidence_target: 0.75

  mature_phase:
    min_applications: 16
    confidence_target: 0.8

  deprecated_phase:
    confidence_threshold: 0.2
    grace_period_days: 30

# Quality Gate Integration
# How confidence affects quality gate enforcement
quality_gate_integration:
  high_confidence_boost: 0.1    # Confidence bonus for high-confidence patterns
  low_confidence_penalty: -0.1  # Confidence penalty for low-confidence patterns
  gate_success_bonus: 0.02     # Confidence bonus when gates pass
  gate_failure_penalty: -0.05  # Confidence penalty when gates fail

# Performance Tuning
performance_tuning:
  confidence_cache_ttl_minutes: 30
  batch_update_size: 10
  max_history_entries: 100
  cleanup_interval_days: 7

# Monitoring and Alerting
monitoring:
  confidence_drop_alert_threshold: 0.1
  low_confidence_alert_threshold: 0.4
  high_success_alert_threshold: 0.95
  pattern_deprecation_alert_enabled: true

# A/B Testing Configuration
ab_testing:
  enabled: true
  test_percentage: 0.1        # 10% of applications use experimental parameters
  test_duration_days: 30
  success_threshold: 0.05     # 5% improvement required to adopt new parameters
  confidence_weight: 0.8      # Weight given to confidence in A/B decisions

# Pattern Type Specific Configuration
pattern_type_config:
  security:
    initial_confidence: 0.6
    success_increment: 0.08
    failure_decrement: 0.15
    requires_human_approval: true

  performance:
    initial_confidence: 0.55
    success_increment: 0.12
    failure_decrement: 0.18
    max_applications_per_session: 5

  architecture:
    initial_confidence: 0.5
    success_increment: 0.06
    failure_decrement: 0.25
    requires_human_approval: true

  quality:
    initial_confidence: 0.52
    success_increment: 0.09
    failure_decrement: 0.16
    max_applications_per_session: 4

  integration:
    initial_confidence: 0.48
    success_increment: 0.11
    failure_decrement: 0.22
    cooldown_period_minutes: 45

  deployment:
    initial_confidence: 0.5
    success_increment: 0.07
    failure_decrement: 0.2
    requires_human_approval: true

# Context Expansion Rules
context_expansion:
  enabled: true
  success_threshold: 0.8      # Success rate required for expansion
  min_similar_contexts: 3     # Minimum similar contexts for expansion
  expansion_rate: 0.1         # Rate at which context is expanded
  max_context_fields: 10      # Maximum number of context fields

# Failure Analysis
failure_analysis:
  enabled: true
  max_failure_reasons: 5
  failure_pattern_detection: true
  automatic_recovery_suggestions: true
  failure_context_capture: true

# Learning Integration
learning_integration:
  cross_pattern_learning: true
  pattern_similarity_threshold: 0.7
  learning_transfer_enabled: true
  knowledge_sharing_enabled: true
  organizational_learning: true

# Validation Rules
validation:
  confidence_bounds_check: true
  threshold_ordering_check: true
  parameter_range_check: true
  schema_validation: true
  business_rules_validation: true

# Emergency Overrides
emergency_overrides:
  enabled: true
  circuit_breaker_confidence: 0.3  # Minimum confidence during emergencies
  max_pattern_applications: 1     # Maximum patterns per session during emergencies
  human_approval_required: true   # Force human approval during emergencies

# Logging and Auditing
logging:
  confidence_changes: true
  application_events: true
  adaptation_events: true
  performance_metrics: true
  audit_trail: true
  log_retention_days: 90

# Version and Compatibility
version:
  config_version: "1.0.0"
  compatible_framework_versions: ["1.0.0", "1.1.0"]
  migration_support: true
  backward_compatibility: true

# Documentation
documentation:
  auto_generated: true
  include_examples: true
  parameter_descriptions: true
  change_history: true