# Pattern Application Configuration
# Defines how patterns are discovered, filtered, applied, and managed

# Pattern Discovery
pattern_discovery:
  enabled: true
  discovery_methods:
    - "manual_creation"
    - "automated_detection"
    - "cross_project_learning"
    - "failure_analysis"
    - "success_pattern_extraction"

  automated_detection:
    enabled: true
    detection_triggers:
      - "successful_task_completion"
      - "quality_gate_success"
      - "performance_improvement"
      - "error_resolution"
      - "decision_outcome"

    detection_rules:
      min_occurrences: 3
      success_rate_threshold: 0.75
      confidence_threshold: 0.6
      context_similarity_threshold: 0.8

# Pattern Filtering
pattern_filtering:
  enabled: true
  filter_criteria:
    confidence_threshold: 0.4
    success_rate_threshold: 0.5
    recency_days: 90
    applicability_score_threshold: 0.6

  exclusion_rules:
    - pattern_type: "deprecated"
    - confidence_below: 0.2
    - success_rate_below: 0.3
    - last_failure_within_days: 7
    - requires_human_approval: true

  inclusion_rules:
    - pattern_type: "security"
    - confidence_above: 0.8
    - success_rate_above: 0.9
    - recent_success_within_days: 30

# Pattern Application
pattern_application:
  auto_apply_enabled: true
  recommendation_enabled: true
  experimental_enabled: true

  application_modes:
    auto_apply:
      confidence_threshold: 0.8
      requires_approval: false
      max_concurrent: 3
      cooldown_minutes: 60

    recommendation:
      confidence_threshold: 0.6
      requires_approval: false
      max_concurrent: 5
      cooldown_minutes: 30

    experimental:
      confidence_threshold: 0.4
      requires_approval: true
      max_concurrent: 2
      cooldown_minutes: 120

  application_context:
    validate_context: true
    context_similarity_threshold: 0.7
    required_context_fields: ["project_type", "technology_stack"]
    optional_context_fields: ["team_size", "timeline_pressure", "quality_requirements"]

# Pattern Matching
pattern_matching:
  algorithm: "weighted_similarity"
  weights:
    trigger_conditions: 0.4
    context_match: 0.3
    success_history: 0.2
    quality_impact: 0.1

  similarity_metrics:
    - name: "context_similarity"
      weight: 0.4
      algorithm: "cosine_similarity"
      fields: ["project_type", "technology_stack", "architecture_pattern"]

    - name: "success_pattern_similarity"
      weight: 0.3
      algorithm: "jaccard_similarity"
      fields: ["trigger_conditions", "success_factors"]

    - name: "quality_impact_similarity"
      weight: 0.3
      algorithm: "euclidean_distance"
      fields: ["quality_improvements", "performance_metrics"]

# Pattern Prioritization
pattern_prioritization:
  enabled: true
  prioritization_factors:
    confidence_score: 0.3
    success_rate: 0.25
    recency: 0.2
    context_match: 0.15
    business_impact: 0.1

  priority_buckets:
    critical:
      threshold: 0.9
      max_patterns: 2
      requires_approval: false

    high:
      threshold: 0.8
      max_patterns: 3
      requires_approval: false

    medium:
      threshold: 0.6
      max_patterns: 5
      requires_approval: false

    low:
      threshold: 0.4
      max_patterns: 10
      requires_approval: true

# Pattern Conflicts
pattern_conflicts:
  conflict_detection: true
  conflict_resolution: "prioritize_higher_confidence"

  conflict_types:
    - type: "mutually_exclusive_actions"
      resolution: "highest_confidence_wins"

    - type: "resource_contention"
      resolution: "queue_and_sequence"

    - type: "overlapping_scope"
      resolution: "merge_patterns"

    - type: "contradictory_goals"
      resolution: "human_arbitration"

# Pattern Lifecycle
pattern_lifecycle:
  creation:
    initial_status: "experimental"
    initial_confidence: 0.5
    validation_required: true
    approval_required: false

  validation:
    min_applications: 3
    success_rate_threshold: 0.7
    confidence_threshold: 0.6
    validation_period_days: 30

  promotion:
    to_recommended:
      min_applications: 5
      success_rate_threshold: 0.8
      confidence_threshold: 0.7

    to_auto_apply:
      min_applications: 10
      success_rate_threshold: 0.85
      confidence_threshold: 0.8

  deprecation:
    confidence_threshold: 0.2
    success_rate_threshold: 0.4
    grace_period_days: 30
    archival_required: true

# Pattern Adaptation
pattern_adaptation:
  enabled: true
  adaptation_triggers:
    - trigger: "success_rate_change"
      threshold: 0.1
      action: "update_confidence"

    - trigger: "context_drift"
      threshold: 0.3
      action: "refine_context_matching"

    - trigger: "quality_impact_change"
      threshold: 0.15
      action: "update_quality_weights"

    - trigger: "failure_pattern_detected"
      threshold: 3
      action: "reduce_confidence"

  adaptation_limits:
    max_adaptations_per_day: 5
    adaptation_cooldown_hours: 6
    requires_validation: true

# Pattern Sharing
pattern_sharing:
  cross_project_enabled: true
  sharing_criteria:
    confidence_above: 0.7
    success_rate_above: 0.8
    min_applications: 5
    no_confidential_data: true

  sharing_format: "anonymized_pattern"
  sharing_channels: ["internal_repository", "team_workspace"]
  sharing_frequency: "weekly"

# Performance Optimization
performance_optimization:
  caching_enabled: true
  cache_ttl_minutes: 30
  batch_processing: true
  batch_size: 10
  parallel_processing: true
  max_concurrent_patterns: 5

# Monitoring and Alerting
monitoring:
  application_metrics: true
  success_rate_tracking: true
  conflict_detection: true
  performance_monitoring: true
  alerting:
    low_success_rate_threshold: 0.5
    high_conflict_rate_threshold: 0.1
    performance_degradation_threshold: 0.2

# Security and Compliance
security:
  pattern_validation: true
  access_control: true
  audit_trail: true
  data_sanitization: true
  compliance_checks: ["data_privacy", "security_standards"]

# Integration Settings
integration:
  api_endpoints: true
  webhook_support: true
  real_time_updates: true
  batch_mode_support: true
  offline_mode_support: false

# Customization Options
customization:
  project_specific_rules: true
  team_specific_preferences: true
  environment_specific_settings: true
  user_role_based_access: true
  configurable_thresholds: true

# Logging and Auditing
logging:
  application_events: true
  decision_events: true
  adaptation_events: true
  conflict_events: true
  performance_events: true
  audit_trail: true
  log_retention_days: 90
  log_level: "info"

# Version and Compatibility
version:
  config_version: "1.0.0"
  compatible_framework_versions: ["1.0.0", "1.1.0"]
  migration_support: true
  backward_compatibility: true